# Generated by Django 3.1.1 on 2020-09-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('upload_date', models.DateTimeField(verbose_name='upload datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='key word')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.content')),
            ],
        ),
    ]
