# Generated by Django 3.1.1 on 2020-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='unit price'),
            preserve_default=False,
        ),
    ]
