# Generated by Django 3.1.1 on 2020-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_keyword_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='upload_date',
            field=models.DateField(verbose_name='upload date'),
        ),
    ]
